In [ ]:
###  Data manipulation and analysis with pandas--- this provides a wide range of function in data analysis making it easier to clean,transform and extract insights from data

In [7]:
%pip install openpyxl

Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
ERROR: Could not find a version that satisfies the requirement openpyxl (from versions: none)
ERROR: No matching distribution found for openpyxl

In [1]:
import pandas as pd

In [4]:
import os

print(os.getcwd())

c:\Users\user\OneDrive\Desktop\SABIAH DANKANO\PYTHON\PYTHON DATA ANALYSIS

In [7]:
import os

print("Current folder:", os.getcwd())
print("Files:", os.listdir())

Current folder: c:\Users\user\OneDrive\Desktop\SABIAH DANKANO\PYTHON\PYTHON DATA ANALYSIS
Files: ['Data mnpln with pandas and numpy.ipynb', 'myexcel.xlsx', 'Numpy.ipynb', 'Pandas.ipynb']

In [10]:
import sys
print(sys.executable)

c:\Users\user\AppData\Local\Programs\Python\Python314\python.exe

In [11]:
import importlib.util
print(importlib.util.find_spec("openpyxl"))

None

In [13]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [15]:
import pandas as pd

df = pd.read_excel("myexcel.xlsx")
df.head()

,Month,Financial Year,Fashions Direct,Suburb,State,Postcode,Country,Manager,Category,Buyer,Sales,Year,Day,Month2
0,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Home,Richard Carr,479.02,2016,Friday,January
1,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Juniors,Chester George,149.95,2016,Friday,January
2,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Mens,Bruce Curran,14.00,2016,Friday,January
3,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Juniors,Chester George,12.00,2016,Friday,January
4,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Womens,Amy Buchanan,46.94,2016,Friday,January

In [16]:
 ### FECTH THE first 5 rows of the data frame
df.head(5)

,Month,Financial Year,Fashions Direct,Suburb,State,Postcode,Country,Manager,Category,Buyer,Sales,Year,Day,Month2
0,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Home,Richard Carr,479.02,2016,Friday,January
1,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Juniors,Chester George,149.95,2016,Friday,January
2,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Mens,Bruce Curran,14.00,2016,Friday,January
3,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Juniors,Chester George,12.00,2016,Friday,January
4,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Womens,Amy Buchanan,46.94,2016,Friday,January

In [17]:
df.tail()

,Month,Financial Year,Fashions Direct,Suburb,State,Postcode,Country,Manager,Category,Buyer,Sales,Year,Day,Month2
8,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Kids,Elizabeth Gentry,5.00,2016,Friday,January
9,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Womens,Amy Buchanan,87.99,2016,Friday,January
10,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Kids,Elizabeth Gentry,4.00,2016,Friday,January
11,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Womens,Amy Buchanan,5.00,2016,Friday,January
12,2016-01-01,2015/16,Fashions Direct,Chatswood,NSW,2067,Australia,Jeremy Garcia,Accessories,Maggie Mayer,2.99,2016,Friday,January

In [ ]:
df.describe() ### the statistical function

                     Month  Postcode       Sales    Year
count                   13      13.0   13.000000    13.0
mean   2016-01-01 00:00:00    2067.0   66.592308  2016.0
min    2016-01-01 00:00:00    2067.0   -2.990000  2016.0
25%    2016-01-01 00:00:00    2067.0    5.000000  2016.0
50%    2016-01-01 00:00:00    2067.0   14.000000  2016.0
75%    2016-01-01 00:00:00    2067.0   46.940000  2016.0
max    2016-01-01 00:00:00    2067.0  479.020000  2016.0
std                    NaN       0.0  131.316756     0.0

In [23]:
df.dtypes

Month              datetime64[us]
Financial Year                str
Fashions Direct               str
Suburb                        str
State                         str
Postcode                    int64
Country                       str
Manager                       str
Category                      str
Buyer                         str
Sales                     float64
Year                        int64
Day                           str
Month2                        str
dtype: object

In [25]:
### Handling missing values

In [26]:
df.isnull()

,Month,Financial Year,Fashions Direct,Suburb,State,Postcode,Country,Manager,Category,Buyer,Sales,Year,Day,Month2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().any() ### any missing value

Month              False
Financial Year     False
Fashions Direct    False
Suburb             False
State              False
Postcode           False
Country            False
Manager            False
Category           False
Buyer              False
Sales              False
Year               False
Day                False
Month2             False
dtype: bool

In [28]:
df.isnull().sum()

Month              0
Financial Year     0
Fashions Direct    0
Suburb             0
State              0
Postcode           0
Country            0
Manager            0
Category           0
Buyer              0
Sales              0
Year               0
Day                0
Month2             0
dtype: int64