#### Data EncodinG
##### This is the process of coverting categorical or text data into numbers so that machine learning model can understand and use it 
###### NB: Ml only understand numerical value
##### 1- Nominal/OHE encoding --One hot encodin ---used to represent categorical data as numerical daata
2-Label and Ordinal
3-Target Guided Ordinal

In [2]:
#### NOMINAL ENCODING/OH ENCODING
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [11]:
### create a simple dataframe
df = pd.DataFrame({
    'color':['red','blue','yellow','green','white']
})
df.head()

    color
0     red
1    blue
2  yellow
3   green
4   white

In [18]:
### creating an instance of onehotencoder
encoder=OneHotEncoder()

In [19]:
### perform fit and transform
encoder.fit_transform(df[['color']]).toarray()

array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
import pandas as pd
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   color   5 non-null      str
dtypes: str(1)
memory usage: 195.0 bytes

In [28]:
df.isnull().sum()

color    0
dtype: int64

In [29]:
categorical_columns = ["sex", "smoker", "day", "time"]

In [ ]:
encoder=OneHotEncoder()

In [43]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [44]:
encoded_data = encoder.fit_transform(
    df[categorical_columns]
)

In [46]:
encoder.fit_transform(
    df[categorical_columns]
)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 976 stored elements and shape (244, 10)>

### label Encoding
#### --This is used to encode categorical data as numerical data,they are usually assigned in alphabetical order or base on the frequency of the category

In [49]:
df = pd.DataFrame({
    'color':['red','blue','yellow','green','white']
})
df.head()

    color
0     red
1    blue
2  yellow
3   green
4   white

In [50]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [51]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 4, 1, 3])

In [53]:
lbl_encoder.transform([['blue']])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [54]:
lbl_encoder.transform([['yellow']])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([4])

In [55]:
lbl_encoder.transform([['green']])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

#### ORDINAL ENCODING
##### This is used to encode categorical data that have an intimistic code or ranking,each category is assigned to a numerical value based on its position in the order

In [65]:
## Ordinal encoder 

from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
###

In [60]:
#### create a simple dataframe with an orinal variable
df=pd.DataFrame({
    'size':['small','medium','large','extralarge','largest']
})

In [61]:
df

         size
0       small
1      medium
2       large
3  extralarge
4     largest

In [72]:
### creating an instance
encoder =OrdinalEncoder(categories=[['small','medium','large','extralarge','largest']])

In [73]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [74]:
encoder.transform([['largest']])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[4.]])

##### TARGET GUIDED ORDINAL ENCODING
##### ---This is used to encode categorical variables based on their relationship qith the target variable,mean and median is also used and it usually deals with large data

In [79]:
import pandas as pd
df=pd.DataFrame({
    'city':['lagos','Abuja','kano','Kaduna','Benin'],
    'price':[200,300,400,500,600]
})

In [80]:
df

     city  price
0   lagos    200
1   Abuja    300
2    kano    400
3  Kaduna    500
4   Benin    600

In [81]:
df.groupby('city')['price'].median()

city
Abuja     300.0
Benin     600.0
Kaduna    500.0
kano      400.0
lagos     200.0
Name: price, dtype: float64

In [82]:
df.groupby('city')['price'].median().to_dict()

{'Abuja': 300.0,
 'Benin': 600.0,
 'Kaduna': 500.0,
 'kano': 400.0,
 'lagos': 200.0}

In [86]:
mean_price=df.groupby('city')['price'].mean().to_dict

In [87]:
mean_price

<bound method Series.to_dict of city
Abuja     300.0
Benin     600.0
Kaduna    500.0
kano      400.0
lagos     200.0
Name: price, dtype: float64>

In [ ]:
df['city_encoded']=df['city'].map(mean_price)